###
GET http://localhost:5000/api/product HTTP/1.1

###
POST http://localhost:5000/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "wahedm@gmail9.com",
    "password": "1234579444" 
}

###


POST http://localhost:5000/api/user/register HTTP/1.1
content-type: application/json

{
    "email": "amirHosseinMaleki@gmail.com",
    "password": "1234579444",
    "name":"Amir Hossein",
    "phoneNumber":"09191831635"
}

### 

POST http://localhost:5000/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "amirHosseinMaleki@gmail.com",
    "password": "1234579444" 
}

###

POST http://localhost:5000/api/user/register HTTP/1.1
content-type: application/json

{
    "email": "amiralimaleki@gmail.com",
    "password": "123456789",
    "name":"Amir Ali",
    "phoneNumber":"09191831512"
}

 